### ISSUE TITLE
Custom variables

### ISSUE THREAD

**Issue by RootGeorg** [heiniha/Nagios-Responsive-HTML-Email-Notifications#3]
Hi, i'm working with custom variables at Nagios, so i added the variable "_location" to host definitions.
I want to include this field into the notification so i changed the array in php to:
....
....
$f_service_attempt_state= array_shift($argv);     /*24*/
$f_max_service_attempt_state= array_shift($argv);     /*25*/
$f_all_recipients= array_shift($argv);  /*26*/
**$f_location= array_shift($argv);  /*27*/    <-----------------**

and modified the html code including this field:
`<h2 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:20px; padding-left:5%;">' . $f_location . '</h2>`
But it doesn't work, it's not filled the field into the notification mail..

How can i achieve that?

Thanks!

**Comment by heiniha** [comment]
Hi,

Have you modified the define command section for the host notification, so that you include the _location host variable and send it to the script?

Look at the first define command section in the github readme file, it should help you along the way.
You need to add this $_HOSTLOCATION$ at the end of the define command for passing the variable to the script.

Otherwise let me know and we can look into it together.

Regards,
Heini

**Comment by RootGeorg** [comment]
Hi,
It worked fine! i made a typo with the command definition.

Thanks for your work!
